runtime: python27
api_version: 1
threadsafe: true

builtins:
- appstats: on
- admin_redirect: on
- deferred: on
- remote_api: on

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
- name: MySQLdb
  version: "latest"

inbound_services:
- warmup

env_variables:
    CLOUDSQL_CONNECTION_NAME: dwint1
    CLOUDSQL_USER: jkbowle
    CLOUDSQL_PASSWORD: Idm183as

handlers:
- url: /favicon.ico
  static_files: application/static/img/favicon.ico
  upload: application/static/img/favicon.ico

- url: /robots.txt
  static_files: application/static/robots.txt
  upload: application/static/robots.txt

- url: /gae_mini_profiler/static
  static_dir: lib/gae_mini_profiler/static

- url: /gae_mini_profiler/.*
  script: lib.gae_mini_profiler.main.application

- url: /static
  static_dir: application/static

- url: /syncdw
  script: run.application.app
  login: admin
  
- url: /push_dw
  script: run.application.app
  login: admin
  
- url: /run_dw_task
  script: run.application.app
  login: admin

- url: /.*
  script: run.application.app