'''
Created on Feb 26, 2017

@author: jason
'''

from application.models import Customer, Location
from application.decorators import admin_required

@admin_required
def init_customer_location():
    cust_d = init_customer()
    init_location(cust_d)

def init_customer():
    costco = Customer.get_customer('Costco')
    cust_d = {}
    if not costco:
        # allocate for MyModel without an instance
        first, last = Customer.allocate_ids(135)
        first_range = range(first, last + 1)
        load_customers(cust_d, first_range)

    
    else:
        custs = Customer.query().fetch()
        for cust in custs:
            cust_d[cust.customer_name] = cust.key
    
    return cust_d
        
def init_location(cust_d):
    ahold_jessup = Location.query(Location.location_name == 'Ahold Jessup').get()
    
    if not ahold_jessup:
        load_locations(cust_d)
        
def create_customer(name, _id, inDict):
    inDict[name] = Customer.create_customer(name,_id)
    
        
def load_locations(cust_d):
    Location.create_location('Ahold Jessup','Jessup','20794',96,cust_d['Ahold'])
    Location.create_location('Acme','Denver','17517',202,cust_d['Acme'])
    Location.create_location('Ahold Carlisle','Carlisle','17013',160,cust_d['Ahold'])
    Location.create_location('Ahold Freetown','Assonet','02702',496,cust_d['Ahold'])
    Location.create_location('Ahold Chester','Chester','10918',345,cust_d['Ahold'])
    Location.create_location('Ahold Martins','Williamsburg','23188',123,cust_d['Ahold'])
    Location.create_location('Albertsons','North Salt Lake','84054',2104,cust_d['Albertsons'])
    Location.create_location('Always N Bloom','Fredericksburg','22407',23,cust_d['Always N Bloom'])
    Location.create_location('Ambius','Beltsville','20705-1374',85,cust_d['Ambius'])
    Location.create_location('American Plant','Bethesda','20816',70,cust_d['American Plant'])
    Location.create_location('Battlefield Farms','Rapidan','22733',16,cust_d['Battlefield Farms'])
    Location.create_location('Bauers','Jarrettsville','21084',139,cust_d['Bauers'])
    Location.create_location('Bee Fresh','Saddle Brook','07663',296,cust_d['Bee Fresh'])
    Location.create_location('Bell Elkridge','Elkridge','21075',98,cust_d['Bell Nursery'])
    Location.create_location('Bell Newark','Newark','19711',164,cust_d['Bell Nursery'])
    Location.create_location('Bell Montpelier','Montpelier','23192',59,cust_d['Bell Nursery'])
    Location.create_location('BlooMaker','Waynesboro','22980',82,cust_d['BlooMaker'])
    Location.create_location("Bozzuto's",'North Haven','06473',379,cust_d["Bozzuto's"])
    Location.create_location('Bella Rosa','Hartford CT.','06108',412,cust_d['Bella Rosa'])
    Location.create_location('Baystate Farm Direct','Wilmington MA','01887',517,cust_d['Baystate'])
    Location.create_location('Chadwhick Orchids','Powhatan','23139',83,cust_d['Chadwhick Orchids'])
    Location.create_location('Charlottesville Orchids Society','Charlottesville','22901',50,cust_d['Charlottesville Orchids Society'])
    Location.create_location('Coastal Sunbelt','Stevensburg','22741',94,cust_d['Coastal Sunbelt'])
    Location.create_location('Commonwealth Growers','Culpeper','22701',14,cust_d['Commonwealth Growers'])
    Location.create_location('Curran Brothers','Danvers MA','01923',526,cust_d['Curran Broths.'])
    Location.create_location('Calaresos Farm Stand','Reading MA','01867',514,cust_d['Calaresos'])
    Location.create_location('Costa Farms','Goulds','33170',1047,cust_d['Costa Farms'])
    Location.create_location('Costco MA','Fairfax','22030',50,cust_d['Costco'])
    Location.create_location('Costco PA','Cranberry TWNSHP','16066',282,cust_d['Costco'])
    Location.create_location('Costco Upper SE','Raleigh','27609',246,cust_d['Costco'])
    Location.create_location('Costco Lower SE','Duluth','30096',539,cust_d['Costco'])
    Location.create_location('Costco FL','E. Jacksonville','32246',686,cust_d['Costco'])
    Location.create_location('C&S','Hatfield MA.','01038',456,cust_d['C&S MA.'])
    Location.create_location('C&S Baldwin','Baldwin Fl.','32234',688,cust_d['C&S Baldwin'])
    Location.create_location('Cupp & Cupp','Boston MA.','02118',508,cust_d['Cupp & Cupp'])
    Location.create_location('Cavicchio Grrenhouse','Sudbury MA.','01776',492,cust_d['Cavicchio Greenhouse'])
    Location.create_location('Delaware Valley Jessup','Jessup','20794',96,cust_d['Delaware Valley'])
    Location.create_location('Delaware Valley NJ','Sewell','08080',203,cust_d['Delaware Valley'])
    Location.create_location('Demoulas Market Basket','Andover','01876',521,cust_d['Demoulas Market Basket'])
    Location.create_location('Daves Marketplace','Greenwich RI','02818',462,cust_d['Daves Marketplace'])
    Location.create_location('Etowah','Etowah','28729',425,cust_d['Etowah'])
    Location.create_location('Fall River','Fall River MA.','02720',491,cust_d['Fall River'])
    Location.create_location('Farm Fresh','Virginia Beach','23464',171,cust_d['Farm Fresh'])
    Location.create_location('Flavor','Culpeper','22701',10,cust_d['Flavor'])
    Location.create_location('Fleurametz Boston','Boston','02118',505,cust_d['Fleurametz'])
    Location.create_location('Flora Max','Richmond','23230',76,cust_d['FloraMax'])
    Location.create_location('Floradise Orchids','Gordonsville','22942',34,cust_d['Floradise'])
    Location.create_location('Floral Distributing, Inc. Des Moines','Des Moines','50321',1042,cust_d['Hy-Vee'])
    Location.create_location('Florist Distributing, Inc Davenport','Davenport','52801',875,cust_d['Hy-Vee'])
    Location.create_location('Florist Distributing, Inc Omaha','Omaha','68144',1183,cust_d['Hy-Vee'])
    Location.create_location('Florist Distributing Inc  Independ.','Independence','64055',1038,cust_d['Hy-Vee'])
    Location.create_location('Florist Distributing Inc  Columbia','Columbia','65202',925,cust_d['Hy-Vee'])
    Location.create_location('Flower Girl','Petersburg','23803',102,cust_d['Flower Girl'])
    Location.create_location('Foliera','Beamsville ON','LOR 1B1',448,cust_d['Foliera'])
    Location.create_location('Fresh 2O','Stevensburg','22741',1,cust_d['Fresh2o'])
    Location.create_location('Fresh Blooms','Jessup','20794',97,cust_d['Fresh Blooms'])
    Location.create_location('Fresh Tulips','King George','22485',36,cust_d['Fresh Tulips'])
    Location.create_location('Floranation','Washington DC.','20018',81,cust_d['Floranation'])
    Location.create_location('Gentle Gardener','Gordonsville','22942',34,cust_d['Gentle Gardener'])
    Location.create_location('Geremia Greenhouses','Wallingford','06492',390,cust_d['Geremia Greenhouses'])
    Location.create_location('Giant 2743','Springfield','22151',58,cust_d['Ahold'])
    Location.create_location('Giant 6439','Richmond','23226',79,cust_d['Ahold'])
    Location.create_location('Giant 6440','Richmond','23236',86,cust_d['Ahold'])
    Location.create_location('Ginkgo Gardens','Washington','20003',77,cust_d['Ginkgo Gardens'])
    Location.create_location('Great Big Greenhouse','Richmond','23235',86,cust_d['Great Big Greenhouse'])
    Location.create_location('Great Lakes Growers','Burton','44021',366,cust_d['Great Lakes Growers'])
    Location.create_location('Green Circle','Oberlin','44074',418,cust_d['Green Circle'])
    Location.create_location('Green Works','','',49,cust_d['Green Works'])
    Location.create_location('Harris Teeter #132','Charlottesville','22911',54,cust_d['Harris Teeter'])
    Location.create_location('Harris Teeter #177','Charlottesville','22905',58,cust_d['Harris Teeter'])
    Location.create_location('Homestead Gardens','Davidsonville','21035',98,cust_d['Homestead Gardens'])
    Location.create_location('Homestead Gardens','Severna Park','21146',116,cust_d['Homestead Gardens'])
    Location.create_location('Idylewilde Farms','Acton MA.','01720',500,cust_d['Idylewilde Farms'])
    Location.create_location('Jan Williams Florals','Stevensburg','22741',26,cust_d['Jan Williams'])
    Location.create_location("Johnson's Kensington",'Kensington','20895',75,cust_d['Johnsons'])
    Location.create_location("Johnson's Olny",'Olney','20832',85,cust_d['Johnsons'])
    #Location.create_location('Johnsons','','',,cust_d['Johnsons'])
    Location.create_location('Johnsons, DC','Washington','20016',72,cust_d['Johnsons'])
    Location.create_location('Key Floral','Bedford','03110',541,cust_d['Key Floral'])
    Location.create_location('Kroger 504','Richmond','23221',77,cust_d['Kroger'])
    Location.create_location('Kroger Dsd','Salem','21543',174,cust_d['Kroger'])
    Location.create_location('Kroger GA','Forest Park','30297',624,cust_d['Kroger'])
    Location.create_location('Kroger Rasc','West Liberty','43357',465,cust_d['Kroger'])
    Location.create_location('Kroger Sfc','Simpsonville','29680',420,cust_d['Kroger'])
    Location.create_location('Kroger TN','Memephis','38141',783,cust_d['Kroger'])
    Location.create_location('Live Trends Design','Apopka','32703',821,cust_d['Live Trends'])
    Location.create_location('Mayflowers','Reston','20190',59,cust_d['Mayflowers'])
    Location.create_location('Meadows Farms','','',50,cust_d['Meadows Farms'])
    Location.create_location("Merrymen's/Fredericksburg Flowers",'Fredericksburg','22401',25,cust_d['Merrymens'])
    Location.create_location('Metrolina','Huntersville','28078',309,cust_d['Metrolina'])
    Location.create_location('Metropolitan Plant Exchange','Fort Lee','07024',300,cust_d['Metropolitan'])
    Location.create_location('Metropolitan Wholesale','Saddlebrook','07663',303,cust_d['Metropolitan'])
    Location.create_location('Moerings','Culpeper','22701',5,cust_d['Moerings'])
    Location.create_location('MH Logistics','Linden NJ','07036',210,cust_d['MH Logistics'])
    Location.create_location('Matsui','Sewell NJ','08080',201,cust_d['Matsui'])
    Location.create_location('Mahoneys','Winchester','01890',512,cust_d['Mahoneys'])
    Location.create_location('Mahoneys Osterville','Osterville','02655',545,cust_d['Osterville'])
    Location.create_location('Mahoneys Brighton','Brighton','02135',502,cust_d['Brighton'])
    Location.create_location('Mahoneys Concord','Concord','01742',500,cust_d['Concord'])
    Location.create_location('Mahoneys Tewksbury','Tewksbury','01876',515,cust_d['Tewksbury'])
    Location.create_location('Mahoneys Chelmsford','Chelmsford','01863',509,cust_d['Chelmsford'])
    Location.create_location('Norfolk Florist','Virginia Beach','23455',165,cust_d['Norfolk Florist'])
    Location.create_location('Oasis Plantscaping','Ashburn','7034340602',55,cust_d['Oasis Plantscaping'])
    Location.create_location('Orchid Station','Barboursville','22923',44,cust_d['Orchid Station'])
    Location.create_location('Orchids For You','Vienna','22180',58,cust_d['Orchids for You'])
    Location.create_location('Ovando','New York','10038',296,cust_d['Ovando'])
    Location.create_location('Palace Florist','Rockville','20852',75,cust_d['Palace Florist'])
    Location.create_location('Patuxant Nursery','Bowie','20716',95,cust_d['Patuxant Nursery'])
    Location.create_location('Pittman Florist','Stevensburg','22741',9,cust_d['Pittman Florist'])
    Location.create_location('Plant Farm Rentals, LLC','Laplata','20646',66,cust_d['Plant Farm Rentals'])
    #Location.create_location('Plant Thanks','','',,cust_d['Plant Thanks'])
    Location.create_location('Plant Works Inc','Chantilly','20151',60,cust_d['Plant Works'])
    Location.create_location('Potomac Floral Wholesale, Inc','Silver Spring','20910',76,cust_d['Potomac Floral'])
    Location.create_location('Premier Plantscapes','Burtonsville','20866',86,cust_d['Premier Plantscapes'])
    Location.create_location('Produce Junction','Swedesboro','08085',190,cust_d['Produce Junction'])
    Location.create_location('Provide Commerce','','',2622,cust_d['Provide Commerce'])
    Location.create_location('R & R Produce','Levittown','19057',229,cust_d['R&R Produce'])
    Location.create_location('Roche Bros','Boston','02118',508,cust_d['Roche Bros'])
    Location.create_location('Roy Houff Norfolk','Norfolk','23502',164,cust_d['Roy Houff'])
    Location.create_location('Roy Houff Richmond','Stevensburg','22741',80,cust_d['Roy Houff'])
    Location.create_location('Rawlings Conservatory','Baltimore MD.','21217',111,cust_d['Rawlings'])
    Location.create_location('Rolling Greens','Clinton MD.','20735',82,cust_d['Rolling Greens'])
    Location.create_location('R &C','Ludlow MA.','01056',448,cust_d['R & C '])
    Location.create_location('Shaws','Brockton MA.','02301',517,cust_d['Shaws'])
    Location.create_location('Safeway','Pleasanton','94588-3299',2835,cust_d['Safeway'])
    Location.create_location('Safeway Hanover Md','Hanover','21076',100,cust_d['Safeway'])
    Location.create_location('Safeway Upper Marlboro','Upper Marlboro','20774',94,cust_d['Safeway'])
    Location.create_location('SKH Distributors','Manheim','17545',189,cust_d['SKH'])
    Location.create_location('Southern Season','Mount Pleasant','29464',507,cust_d['Southern Seasons'])
    Location.create_location("Stew Leonard's of Norwalk",'Norwalk','06851',344,cust_d['Stew Leonards'])
    Location.create_location("Strange's",'Richmond','23233',80,cust_d['Stranges'])
    Location.create_location('Streets Market Cafe','Washington','20009',72,cust_d['Streets Market'])
    Location.create_location('Streets Market Cafe Alexandria','Alexandria','22305',72,cust_d['Streets Market'])
    Location.create_location('Streets Market Cafe Arlington','Arlington','22201',69,cust_d['Streets Market'])
    Location.create_location('TFS Roanoke, Inc','Roanoke','24018',170,cust_d['TFS'])
    Location.create_location('The Great Big Greenhouse','Richmond','23235',86,cust_d['Great Big Greenhouse'])
    Location.create_location('The Orchid Place','Ithaca','14850',409,cust_d['Orchid Place'])
    Location.create_location('The Plant Company of Ohio','Milton','17847',493,cust_d['The Plant Company of Ohio'])
    Location.create_location('The Plant People','Stevensburg','22741',35,cust_d['The Plant People'])
    Location.create_location('Tom Leonards','Glen Allen','23060',80,cust_d['Tom Leonards'])
    Location.create_location("Trader Joe's Daytona WH",'Daytona Beach','32117',768,cust_d['Trader Joes'])
    Location.create_location('Towell Media','Bloomfield NJ','07003',295,cust_d['Towell Media'])
    Location.create_location('van Hoekelen Greenhouses','Mcadoo','18237',254,cust_d['Van Hoekelen'])
    Location.create_location('Van Wingerden International, Inc.','Mills River','28759',420,cust_d['VWI'])
    Location.create_location('Virginia Floral','Fredericksburg','22408',24,cust_d['Virginia Floral'])
    Location.create_location('VM Signature','Burke','22015',59,cust_d['VM Signature'])
    Location.create_location('Villanova','Villanova Pa.','19085',207,cust_d['Villanova'])
    Location.create_location('Wakefern','Elizabeth','07207',283,cust_d['Wakefern'])
    Location.create_location('Wakefern','Newark','07105',288,cust_d['Wakefern'])
    Location.create_location('Washington Landscapes LLC','Fairfax','22031',58,cust_d['Washington Landscapes'])
    Location.create_location('Wegmans','Rochester','14603',438,cust_d['Wegmans'])
    Location.create_location('Wegmans Bel Air','Abingdon','21009',132,cust_d['Wegmans'])
    Location.create_location('Wegmans Columbia','Columbia','21045',97,cust_d['Wegmans'])
    Location.create_location('Wegmans Crofton','Gambrills','21054',104,cust_d['Wegmans'])
    Location.create_location('Wegmans Dulles','Sterling','20166',59,cust_d['Wegmans'])
    Location.create_location('Wegmans Fairfax','Fairfax','22030',53,cust_d['Wegmans'])
    Location.create_location('Wegmans Frederick','Frederick','21701',87,cust_d['Wegmans'])
    Location.create_location('Wegmans Fredericksburg','Fredericksburg','22401',25,cust_d['Wegmans'])
    Location.create_location('Wegmans Germantown','Germantown','20876',84,cust_d['Wegmans'])
    Location.create_location('Wegmans Hunt Valley','Hunt Valley','21030',126,cust_d['Wegmans'])
    Location.create_location('Wegmans Lake Manassas','Gainsville','20155',33,cust_d['Wegmans'])
    Location.create_location('Wegmans Leesburg','Leesburg','20175',61,cust_d['Wegmans'])
    Location.create_location('Wegmans Potomac','Woodbridge','22191',51,cust_d['Wegmans'])
    Location.create_location('Wegmans Pottsville','Pottsville','17901',232,cust_d['Wegmans'])
    Location.create_location('Wegmans Woodmore','Lanham','20706',89,cust_d['Wegmans'])
    Location.create_location('Whole Foods #57 Alexandria','Alexandria','22314',65,cust_d['Whole Foods'])
    Location.create_location('Whole Foods Ashburn#81','Ashburn','20147',64,cust_d['Whole Foods'])
    Location.create_location('Whole foods ASI','','',0,cust_d['Whole Foods'])
    Location.create_location('Whole Foods CV','Charlottesville','22901',51,cust_d['Whole Foods'])
    Location.create_location('Whole Foods Fairfax','Fairfax','22033',50,cust_d['Whole Foods'])
    Location.create_location('Whole Foods Falls Church','Falls Church','22043',61,cust_d['Whole Foods'])
    Location.create_location('Whole Foods FB','Washington','20003',77,cust_d['Whole Foods'])
    Location.create_location('Whole Foods MA','Landover','20785',86,cust_d['Whole Foods'])
    Location.create_location('Whole Foods Market# 84','Newport News','23606',140,cust_d['Whole Foods'])
    Location.create_location('Whole Foods Reston','Reston','20191',58,cust_d['Whole Foods'])
    Location.create_location('Whole Foods Rockville MD','Rockville','20852',72,cust_d['Whole Foods'])
    Location.create_location('Whole Foods SPP','Glen Allen','02060',80,cust_d['Whole Foods'])
    Location.create_location('Whole Foods Vienna','Vienna','22180',58,cust_d['Whole Foods'])
    Location.create_location('Whole Foods Virginia Beach','Virginia Beach','23454',177,cust_d['Whole Foods'])
    Location.create_location('Whole Foods Washington DC','Washington','20037',69,cust_d['Whole Foods'])
    Location.create_location('WholeFoods Gaithersburg','Gaithersburg','20878',80,cust_d['Whole Foods'])
    Location.create_location('Whole Foods PA.','Allentown Pa.','18106',258,cust_d['Whole Foods'])
    Location.create_location('Whole Foods GA.','Braselton Ga.','30157',521,cust_d['Whole Foods'])
    Location.create_location('Whole Foods MA.','Hingham MA.','02043',522,cust_d['Whole Foods'])
    Location.create_location('Willow Run Greenhouse','Culpeper','22701',12,cust_d['Willow Run'])
    Location.create_location('Willow Oak Flowers','Severn MD.','21144',94,cust_d['Willow Oak'])
    Location.create_location('Whole Bunch','Burlington MA.','01803',512,cust_d['Whole Bunch'])
    Location.create_location('Winston Flowers','Boston Ma.','02118',509,cust_d['Winston Flowers'])
    Location.create_location("Wilson's",'Lexington MA.','02421',505,cust_d["Wilson's"])
    Location.create_location('Price Chopper','Schenectady','12308',450,cust_d['Price Chopper'])
    Location.create_location('Publix','','33811',891,cust_d['Publix'])
    Location.create_location('Wise Services & Recycling','Culpeper','22701',24,cust_d['Wise Services'])
    Location.create_location('United Orchids','Middletown NY','10941',360,cust_d['United Orchids'])
    Location.create_location('183','ALTAMONTE','32714',810,cust_d['Costco'])
    Location.create_location('184','S. ORLANDO','32837',830,cust_d['Costco'])
    Location.create_location('185','E. ORLANDO','32792',819,cust_d['Costco'])
    Location.create_location('187','DULUTH','30096',539,cust_d['Costco'])
    Location.create_location('188','PEACHTREE','30328',555,cust_d['Costco'])
    Location.create_location('189','KENNESAW','30144',573,cust_d['Costco'])
    Location.create_location('202','NORFOLK','23502',181,cust_d['Costco'])
    Location.create_location('203','GLEN BURNIE','21060',119,cust_d['Costco'])
    Location.create_location('204','FAIRFAX','22030',50,cust_d['Costco'])
    Location.create_location('205','HENRICO','23060',83,cust_d['Costco'])
    Location.create_location('208','WHITE MAR.','21220',131,cust_d['Costco'])
    Location.create_location('213','GAITHERSBURG','20879',94,cust_d['Costco'])
    Location.create_location('214','BELTSVILLE','20705',97,cust_d['Costco'])
    Location.create_location('218','STERLING','20164',60.2,cust_d['Costco'])
    Location.create_location('225','MANASSAS','20109',37,cust_d['Costco'])
    Location.create_location('227','NEWINGTON','22153',62,cust_d['Costco'])
    Location.create_location('233','PENTAGON','22202',73,cust_d['Costco'])
    Location.create_location('238','HARRISONBURG','22801',70,cust_d['Costco'])
    Location.create_location('239','WINCHESTER','22602',65,cust_d['Costco'])
    Location.create_location('247','NEWPORT NWS','23602',151,cust_d['Costco'])
    Location.create_location('249','DURHAM','27705',229,cust_d['Costco'])
    Location.create_location('317','LANCASTER','17601',202,cust_d['Costco'])
    Location.create_location('325','ARUNDEL MLLS','21076',108,cust_d['Costco'])
    Location.create_location('327','HARRISBURG','17112',186,cust_d['Costco'])
    Location.create_location('328','CRANBERRY','16066',281,cust_d['Costco'])
    Location.create_location('330','FREDERICK','21704',93,cust_d['Costco'])
    Location.create_location('332','ROBINSON','15205',278,cust_d['Costco'])
    Location.create_location('334','CHANTILLY','21051',50,cust_d['Costco'])
    Location.create_location('336','CLEARWATER','33759',889,cust_d['Costco'])
    Location.create_location('337','LEESBURG','20176',59,cust_d['Costco'])
    Location.create_location('338','MYRTLE BEACH','29577',339,cust_d['Costco'])
    Location.create_location('339','GREENSBORO','27407',235,cust_d['Costco'])
    Location.create_location('340','FREDRICKBURG','22407',23,cust_d['Costco'])
    Location.create_location('351','FT. MYERS','33907',1003,cust_d['Costco'])
    Location.create_location('352','N.E. MEMPHIS','38018',788,cust_d['Costco'])
    Location.create_location('353','S.E. MEMPHIS','38125',806,cust_d['Costco'])
    Location.create_location('354','NAPLES','34109',1025,cust_d['Costco'])
    Location.create_location('356','HUNTSVILLE','35801',628,cust_d['Costco'])
    Location.create_location('357','E. JACKSONVILLE','32246',686,cust_d['Costco'])
    Location.create_location('358','BRANDON','33511',875,cust_d['Costco'])
    Location.create_location('359','CHARLOTTE','28217',327,cust_d['Costco'])
    Location.create_location('360','CHARLESTON','29414',500,cust_d['Costco'])
    Location.create_location('361','WINSTON SAL.','27103',263,cust_d['Costco'])
    Location.create_location('362','HOOVER','35244',681,cust_d['Costco'])
    Location.create_location('366','BUFORD','30519',527,cust_d['Costco'])
    Location.create_location('367','MATTHEWS','28105',331,cust_d['Costco'])
    Location.create_location('386','BRENTWOOD','37027',607,cust_d['Costco'])
    Location.create_location('621','FT. MYERS','33913',1003,cust_d['Costco'])
    Location.create_location('626','POTOMAC MLLS','22192',53,cust_d['Costco'])
    Location.create_location('630','W. NASHVILLE','37209',602,cust_d['Costco'])
    Location.create_location('631','CUMBERLAND','30339',560,cust_d['Costco'])
    Location.create_location('635','WILMINGTON','28405',332,cust_d['Costco'])
    Location.create_location('645','RALEIGH','27609',246,cust_d['Costco'])
    Location.create_location('649','HOMESTEAD','15120',265,cust_d['Costco'])
    Location.create_location('743','ALPHARETTA','30004',546,cust_d['Costco'])
    Location.create_location('1000','COLUMBIA','21075',110,cust_d['Costco'])
    Location.create_location('1005','GREENVILLE','29607',413,cust_d['Costco'])
    Location.create_location('1008','SPARTANBURG','29301',397,cust_d['Costco'])
    Location.create_location('1009','MONTGOMERY','36117',712,cust_d['Costco'])
    Location.create_location('1026','TALLAHASSEE','32317',833,cust_d['Costco'])
    Location.create_location('1039','BRANDYWINE','20613',82,cust_d['Costco'])
    Location.create_location('1078','LANHAM','20706',89,cust_d['Costco'])
    Location.create_location('1083','RINGGOLD','30736',523,cust_d['Costco'])
    Location.create_location('1084','BROOKHAVEN','30319',552,cust_d['Costco'])
    Location.create_location('1089','CHESTERFIELD','23235',91,cust_d['Costco'])
    Location.create_location('1102','AUGUSTA','30909',481,cust_d['Costco'])
    Location.create_location('1115','MT. VERNON','22306',65,cust_d['Costco'])
    Location.create_location('1116','FARRAGUT','37934',431,cust_d['Costco'])
    Location.create_location('1120','WASHINGTON','20018',85,cust_d['Costco'])
    Location.create_location('1123','SARASOTA','34238',930,cust_d['Costco'])
    Location.create_location('1124','WHEATON','20902',90,cust_d['Costco'])
    Location.create_location('1175','CUMMING','',543,cust_d['Costco'])
    Location.create_location('1192','MOBILE','22901',891,cust_d['Costco'])
    Location.create_location('1184',"C'VILLE",'',51.3,cust_d['Costco'])
    Location.create_location('1206','Apex','27523',260,cust_d['Costco'])
    Location.create_location('1232','COLUMBIA','29210',458,cust_d['Costco'])
    Location.create_location('1235','Orlando','32839',822,cust_d['Costco'])
    Location.create_location('1249','Lutz','33559',855,cust_d['Costco'])
    Location.create_location('1262','Tampa','33625',875,cust_d['Costco'])



def load_customers(cust_d, first_range):
    create_customer('Acme', first_range.pop(), cust_d)
    create_customer('Ahold', first_range.pop(), cust_d)
    create_customer('Albertsons', first_range.pop(), cust_d)
    create_customer('Always N Bloom', first_range.pop(), cust_d)
    create_customer('Ambius', first_range.pop(), cust_d)
    create_customer('American Plant', first_range.pop(), cust_d)
    create_customer('Battlefield Farms', first_range.pop(), cust_d)
    create_customer('Bauers', first_range.pop(), cust_d)
    create_customer('Baystate', first_range.pop(), cust_d)
    create_customer('Bee Fresh', first_range.pop(), cust_d)
    create_customer('Bell Nursery', first_range.pop(), cust_d)
    create_customer('Bella Rosa', first_range.pop(), cust_d)
    create_customer('BlooMaker', first_range.pop(), cust_d)
    create_customer("Bozzuto's", first_range.pop(), cust_d)
    create_customer('Brighton', first_range.pop(), cust_d)
    create_customer('C&S Baldwin', first_range.pop(), cust_d)
    create_customer('C&S MA.', first_range.pop(), cust_d)
    create_customer('Calaresos', first_range.pop(), cust_d)
    create_customer('Cavicchio Greenhouse', first_range.pop(), cust_d)
    create_customer('Chadwhick Orchids', first_range.pop(), cust_d)
    create_customer('Charlottesville Orchids Society', first_range.pop(), cust_d)
    create_customer('Chelmsford', first_range.pop(), cust_d)
    create_customer('Coastal Sunbelt', first_range.pop(), cust_d)
    create_customer('Commonwealth Growers', first_range.pop(), cust_d)
    create_customer('Concord', first_range.pop(), cust_d)
    create_customer('Costa Farms', first_range.pop(), cust_d)
    create_customer('Costco', first_range.pop(), cust_d)
    create_customer('Cupp & Cupp', first_range.pop(), cust_d)
    create_customer('Curran Broths.', first_range.pop(), cust_d)
    create_customer('Daves Marketplace', first_range.pop(), cust_d)
    create_customer('Delaware Valley', first_range.pop(), cust_d)
    create_customer('Demoulas Market Basket', first_range.pop(), cust_d)
    create_customer('Etowah', first_range.pop(), cust_d)
    create_customer('Fall River', first_range.pop(), cust_d)
    create_customer('Farm Fresh', first_range.pop(), cust_d)
    create_customer('Flavor', first_range.pop(), cust_d)
    create_customer('Fleurametz', first_range.pop(), cust_d)
    create_customer('Floradise', first_range.pop(), cust_d)
    create_customer('FloraMax', first_range.pop(), cust_d)
    create_customer('Floranation', first_range.pop(), cust_d)
    create_customer('Flower Girl', first_range.pop(), cust_d)
    create_customer('Foliera', first_range.pop(), cust_d)
    create_customer('Fresh Blooms', first_range.pop(), cust_d)
    create_customer('Fresh Tulips', first_range.pop(), cust_d)
    create_customer('Fresh2o', first_range.pop(), cust_d)
    create_customer('Gentle Gardener', first_range.pop(), cust_d)
    create_customer('Geremia Greenhouses', first_range.pop(), cust_d)
    create_customer('Ginkgo Gardens', first_range.pop(), cust_d)
    create_customer('Great Big Greenhouse', first_range.pop(), cust_d)
    create_customer('Great Lakes Growers', first_range.pop(), cust_d)
    create_customer('Green Circle', first_range.pop(), cust_d)
    create_customer('Green Works', first_range.pop(), cust_d)
    create_customer('Harris Teeter', first_range.pop(), cust_d)
    create_customer('Homestead Gardens', first_range.pop(), cust_d)
    create_customer('Hy-Vee', first_range.pop(), cust_d)
    create_customer('Idylewilde Farms', first_range.pop(), cust_d)
    create_customer('Jan Williams', first_range.pop(), cust_d)
    create_customer('Johnsons', first_range.pop(), cust_d)
    create_customer('Key Floral', first_range.pop(), cust_d)
    create_customer('Kroger', first_range.pop(), cust_d)
    create_customer('Live Trends', first_range.pop(), cust_d)
    create_customer('Mahoneys', first_range.pop(), cust_d)
    create_customer('Matsui', first_range.pop(), cust_d)
    create_customer('Mayflowers', first_range.pop(), cust_d)
    create_customer('Meadows Farms', first_range.pop(), cust_d)
    create_customer('Merrymens', first_range.pop(), cust_d)
    create_customer('Metrolina', first_range.pop(), cust_d)
    create_customer('Metropolitan', first_range.pop(), cust_d)
    create_customer('MH Logistics', first_range.pop(), cust_d)
    create_customer('Moerings', first_range.pop(), cust_d)
    create_customer('Norfolk Florist', first_range.pop(), cust_d)
    create_customer('Oasis Plantscaping', first_range.pop(), cust_d)
    create_customer('Orchid Place', first_range.pop(), cust_d)
    create_customer('Orchid Station', first_range.pop(), cust_d)
    create_customer('Orchids for You', first_range.pop(), cust_d)
    create_customer('Osterville', first_range.pop(), cust_d)
    create_customer('Ovando', first_range.pop(), cust_d)
    create_customer('Palace Florist', first_range.pop(), cust_d)
    create_customer('Patuxant Nursery', first_range.pop(), cust_d)
    create_customer('Pittman Florist', first_range.pop(), cust_d)
    create_customer('Plant Farm Rentals', first_range.pop(), cust_d)
    create_customer('Plant Thanks', first_range.pop(), cust_d)
    create_customer('Plant Works', first_range.pop(), cust_d)
    create_customer('Potomac Floral', first_range.pop(), cust_d)
    create_customer('Premier Plantscapes', first_range.pop(), cust_d)
    create_customer('Price Chopper', first_range.pop(), cust_d)
    create_customer('Produce Junction', first_range.pop(), cust_d)
    create_customer('Provide Commerce', first_range.pop(), cust_d)
    create_customer('Publix', first_range.pop(), cust_d)
    create_customer('R & C ', first_range.pop(), cust_d)
    create_customer('R&R Produce', first_range.pop(), cust_d)
    create_customer('Rawlings', first_range.pop(), cust_d)
    create_customer('Roche Bros', first_range.pop(), cust_d)
    create_customer('Rolling Greens', first_range.pop(), cust_d)
    create_customer('Roy Houff', first_range.pop(), cust_d)
    create_customer('Safeway', first_range.pop(), cust_d)
    create_customer('Shaws', first_range.pop(), cust_d)
    create_customer('SKH', first_range.pop(), cust_d)
    create_customer('Southern Seasons', first_range.pop(), cust_d)
    create_customer('Stew Leonards', first_range.pop(), cust_d)
    create_customer('Stranges', first_range.pop(), cust_d)
    create_customer('Streets Market', first_range.pop(), cust_d)
    create_customer('Tewksbury', first_range.pop(), cust_d)
    create_customer('TFS', first_range.pop(), cust_d)
    create_customer('The Plant Company of Ohio', first_range.pop(), cust_d)
    create_customer('The Plant People', first_range.pop(), cust_d)
    create_customer('Tom Leonards', first_range.pop(), cust_d)
    create_customer('Towell Media', first_range.pop(), cust_d)
    create_customer('Trader Joes', first_range.pop(), cust_d)
    create_customer('United Orchids', first_range.pop(), cust_d)
    create_customer('Van Hoekelen', first_range.pop(), cust_d)
    create_customer('Villanova', first_range.pop(), cust_d)
    create_customer('Virginia Floral', first_range.pop(), cust_d)
    create_customer('VM Signature', first_range.pop(), cust_d)
    create_customer('VWI', first_range.pop(), cust_d)
    create_customer('Wakefern', first_range.pop(), cust_d)
    create_customer('Washington Landscapes', first_range.pop(), cust_d)
    create_customer('Wegmans', first_range.pop(), cust_d)
    create_customer('Whole Bunch', first_range.pop(), cust_d)
    create_customer('Whole Foods', first_range.pop(), cust_d)
    create_customer('Willow Oak', first_range.pop(), cust_d)
    create_customer('Willow Run', first_range.pop(), cust_d)
    create_customer("Wilson's", first_range.pop(), cust_d)
    create_customer('Winston Flowers', first_range.pop(), cust_d)
    create_customer('Wise Services', first_range.pop(), cust_d)
    create_customer('Grand Total', first_range.pop(), cust_d)


